"""Initial migration: create portfolios, positions, reports, stock_data_cache tables

Revision ID: 4a41fdb03e69
Revises: 
Create Date: 2025-11-28 22:57:21.178638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a41fdb03e69'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID（预留多用户支持）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='组合名称'),
    sa.Column('total_assets', sa.Numeric(precision=15, scale=2), nullable=False, comment='总资产'),
    sa.Column('description', sa.Text(), nullable=True, comment='组合描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('stock_data_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('date', sa.Date(), nullable=False, comment='日期'),
    sa.Column('open_price', sa.Numeric(precision=10, scale=3), nullable=True, comment='开盘价'),
    sa.Column('high_price', sa.Numeric(precision=10, scale=3), nullable=True, comment='最高价'),
    sa.Column('low_price', sa.Numeric(precision=10, scale=3), nullable=True, comment='最低价'),
    sa.Column('close_price', sa.Numeric(precision=10, scale=3), nullable=False, comment='收盘价'),
    sa.Column('volume', sa.BigInteger(), nullable=True, comment='成交量'),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=True, comment='成交额'),
    sa.Column('indicators', sa.JSON(), nullable=True, comment='技术指标（MA, RSI, MACD, BOLL 等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'date', name='uix_stock_date')
    )
    op.create_index(op.f('ix_stock_data_cache_date'), 'stock_data_cache', ['date'], unique=False)
    op.create_index(op.f('ix_stock_data_cache_id'), 'stock_data_cache', ['id'], unique=False)
    op.create_index(op.f('ix_stock_data_cache_stock_code'), 'stock_data_cache', ['stock_code'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False, comment='所属组合ID'),
    sa.Column('stock_code', sa.String(length=20), nullable=False, comment='股票代码（如 600519.SH）'),
    sa.Column('stock_name', sa.String(length=100), nullable=True, comment='股票名称'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='持仓数量（股）'),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=3), nullable=False, comment='成本价'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_stock_code'), 'positions', ['stock_code'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False, comment='所属组合ID'),
    sa.Column('report_type', sa.String(length=20), nullable=False, comment='报告类型（weekly/daily）'),
    sa.Column('report_date', sa.Date(), nullable=False, comment='报告日期'),
    sa.Column('content', sa.JSON(), nullable=True, comment='结构化内容（LLM 生成的 JSON）'),
    sa.Column('html_content', sa.Text(), nullable=True, comment='HTML 格式内容'),
    sa.Column('pushed', sa.Boolean(), nullable=True, comment='是否已推送'),
    sa.Column('push_time', sa.DateTime(timezone=True), nullable=True, comment='推送时间'),
    sa.Column('push_result', sa.Text(), nullable=True, comment='推送结果'),
    sa.Column('generation_time', sa.Integer(), nullable=True, comment='生成耗时（秒）'),
    sa.Column('llm_tokens', sa.Integer(), nullable=True, comment='LLM 使用的 token 数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_report_date'), 'reports', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_report_date'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_positions_stock_code'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_stock_data_cache_stock_code'), table_name='stock_data_cache')
    op.drop_index(op.f('ix_stock_data_cache_id'), table_name='stock_data_cache')
    op.drop_index(op.f('ix_stock_data_cache_date'), table_name='stock_data_cache')
    op.drop_table('stock_data_cache')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
